-- MySQL Script generated by MySQL Workbench
-- Mon 20 Nov 2017 10:26:37 PM BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema analitico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema analitico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analitico` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vestibular
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vestibular
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vestibular` DEFAULT CHARACTER SET latin1 ;
USE `analitico` ;

-- -----------------------------------------------------
-- Table `analitico`.`dm_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analitico`.`dm_evento` (
  `seq_vestibular` INT NOT NULL AUTO_INCREMENT,
  `id_evento` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  PRIMARY KEY (`seq_vestibular`),
  INDEX `idx_id_evento` (`id_evento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analitico`.`dm_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analitico`.`dm_candidato` (
  `seq_candidato` INT(11) NOT NULL AUTO_INCREMENT,
  `id_candidato` INT(11) NULL,
  `genero` VARCHAR(50) NULL,
  `raca` VARCHAR(50) NULL,
  `dt_segundo_grau` VARCHAR(50) NULL,
  `por_experiencia` VARCHAR(3) NULL,
  `ensino_publico` VARCHAR(3) NULL,
  PRIMARY KEY (`seq_candidato`),
  INDEX `index2` (`id_candidato` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analitico`.`dm_estabelecimento_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analitico`.`dm_estabelecimento_ensino` (
  `seq_estabelecimento_ensino` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estabelecimento` INT NOT NULL,
  `nome_estabelecimento` VARCHAR(45) NULL,
  `cidade` VARCHAR(100) NULL,
  PRIMARY KEY (`seq_estabelecimento_ensino`),
  INDEX `index2` (`id_estabelecimento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analitico`.`dm_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analitico`.`dm_curso` (
  `seq_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `id_curso` INT NULL,
  `nome_curso` VARCHAR(100) NULL,
  `nome_centro` VARCHAR(100) NULL,
  `area_curso` VARCHAR(100) NULL,
  PRIMARY KEY (`seq_curso`),
  INDEX `idx_id_curso` (`id_curso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analitico`.`dm_socio_economica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analitico`.`dm_socio_economica` (
  `seq_socio_economica` INT NOT NULL AUTO_INCREMENT,
  `estado_civil` VARCHAR(150) NULL,
  `grau_instrucao_pai` VARCHAR(150) NULL,
  `grau_instrucao_mae` VARCHAR(150) NULL,
  `possui_computador` VARCHAR(150) NULL,
  `renda_total` VARCHAR(150) NULL,
  `curso_pre_vestibular` VARCHAR(150) NULL,
  `hash` VARCHAR(100) NULL,
  PRIMARY KEY (`seq_socio_economica`),
  INDEX `index2` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analitico`.`ft_desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analitico`.`ft_desempenho` (
  `dm_vestibular_seq` INT(11) NOT NULL,
  `dm_estabelecimento_ensino_seq` INT(11) NOT NULL,
  `dm_candidato_seq` INT(11) NOT NULL,
  `dm_curso_seq` INT(11) NOT NULL,
  `dm_socio_economica_seq` INT(11) NOT NULL,
  `posicao` DECIMAL(20,2) NULL,
  `classificacao_geral` DECIMAL(20,0) NULL,
  `acertos_total` DECIMAL(20,2) NULL,
  `acertos_matematica` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_biologia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_lingua_estrangeira` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_geografia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_portugues` DECIMAL(5,2) NULL DEFAULT NULL,
  `nota_redacao` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_fisica` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_historia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_quimica` DECIMAL(5,2) NULL DEFAULT NULL,
  `ordem_classificacao` DECIMAL(5,2) NULL,
  `fl_classificado` INT NULL,
  INDEX `fk_ft_desempenho_dm_vestibular_idx` (`dm_vestibular_seq` ASC),
  INDEX `fk_ft_desempenho_dm_estabelecimento_ensino1_idx` (`dm_estabelecimento_ensino_seq` ASC),
  PRIMARY KEY (`dm_vestibular_seq`, `dm_estabelecimento_ensino_seq`, `dm_candidato_seq`, `dm_curso_seq`, `dm_socio_economica_seq`),
  INDEX `fk_ft_desempenho_dm_candidato1_idx` (`dm_candidato_seq` ASC),
  INDEX `fk_ft_desempenho_dm_curso1_idx` (`dm_curso_seq` ASC),
  INDEX `fk_ft_desempenho_dm_socio_economica1_idx` (`dm_socio_economica_seq` ASC),
  CONSTRAINT `fk_ft_desempenho_dm_vestibular`
    FOREIGN KEY (`dm_vestibular_seq`)
    REFERENCES `analitico`.`dm_evento` (`seq_vestibular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_estabelecimento_ensino1`
    FOREIGN KEY (`dm_estabelecimento_ensino_seq`)
    REFERENCES `analitico`.`dm_estabelecimento_ensino` (`seq_estabelecimento_ensino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_candidato1`
    FOREIGN KEY (`dm_candidato_seq`)
    REFERENCES `analitico`.`dm_candidato` (`seq_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_curso1`
    FOREIGN KEY (`dm_curso_seq`)
    REFERENCES `analitico`.`dm_curso` (`seq_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_socio_economica1`
    FOREIGN KEY (`dm_socio_economica_seq`)
    REFERENCES `analitico`.`dm_socio_economica` (`seq_socio_economica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vestibular` ;

-- -----------------------------------------------------
-- Table `vestibular`.`area_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`area_curso` (
  `id_area` SMALLINT(6) NOT NULL,
  `nome_area` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`centro_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`centro_curso` (
  `id_centro` SMALLINT(6) NOT NULL,
  `nome_centro` VARCHAR(40) NOT NULL,
  `sigla_centro` CHAR(5) NOT NULL,
  PRIMARY KEY (`id_centro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`evento` (
  `id_evento` SMALLINT(6) NOT NULL,
  `descricao_evento` VARCHAR(40) NULL DEFAULT NULL,
  `ano_evento` SMALLINT(6) NULL DEFAULT NULL,
  `acerto_minimo_exigido` TINYINT(4) NULL DEFAULT NULL,
  `media_acertos` DECIMAL(5,2) NULL DEFAULT NULL,
  `numero_inscritos` DECIMAL(6,0) NULL DEFAULT NULL,
  `numero_vagas` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`curso` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_curso` SMALLINT(6) NOT NULL,
  `nome_curso` VARCHAR(60) NULL DEFAULT NULL,
  `id_area` SMALLINT(6) NULL DEFAULT NULL,
  `numero_vagas` SMALLINT(6) NULL DEFAULT NULL,
  `vagas_ocupadas` SMALLINT(6) NULL DEFAULT NULL,
  `id_centro` SMALLINT(6) NULL DEFAULT NULL,
  `opcao1a` CHAR(1) NULL DEFAULT NULL,
  `nome_abreviado` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_curso`),
  INDEX `fk_curso_area_curso` (`id_area` ASC),
  INDEX `fk_curso_centro_curso` (`id_centro` ASC),
  CONSTRAINT `fk_curso_area_curso`
    FOREIGN KEY (`id_area`)
    REFERENCES `vestibular`.`area_curso` (`id_area`),
  CONSTRAINT `fk_curso_centro_curso`
    FOREIGN KEY (`id_centro`)
    REFERENCES `vestibular`.`centro_curso` (`id_centro`),
  CONSTRAINT `fk_curso_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`acertos_questao_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`acertos_questao_curso` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_curso` SMALLINT(6) NOT NULL,
  `id_prova` TINYINT(4) NOT NULL,
  `tipo_prova` TINYINT(4) NOT NULL,
  `numero_questao` TINYINT(4) NOT NULL DEFAULT '0',
  `numero_acertos` DECIMAL(6,0) NULL DEFAULT NULL,
  `numero_acertos_parciais` DECIMAL(6,0) NULL DEFAULT NULL,
  `acertos_aprovados` DECIMAL(6,0) NULL DEFAULT NULL,
  `acertos_parciais_aprovados` DECIMAL(6,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_curso`, `id_prova`, `tipo_prova`, `numero_questao`),
  CONSTRAINT `fk_acertos_questao_curso_curso`
    FOREIGN KEY (`id_evento` , `id_curso`)
    REFERENCES `vestibular`.`curso` (`id_evento` , `id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`boletim_desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`boletim_desempenho` (
  `id_evento` DECIMAL(10,0) NOT NULL,
  `id_candidato` DECIMAL(7,0) NOT NULL,
  `acertos_matematica` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_biologia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_lingua_estrangeira` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_geografia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_portugues` DECIMAL(5,2) NULL DEFAULT NULL,
  `nota_redacao` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_fisica` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_historia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_quimica` DECIMAL(5,2) NULL DEFAULT NULL,
  `id_opcao1` SMALLINT(6) NULL DEFAULT NULL,
  `id_opcao2` SMALLINT(6) NULL DEFAULT NULL,
  `id_opcao1a` SMALLINT(6) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `unidade_federativa` CHAR(2) NULL DEFAULT NULL,
  `classificacao_geral` DECIMAL(6,0) NULL DEFAULT NULL,
  `posicao_1` DECIMAL(5,0) NULL DEFAULT NULL,
  `posicao_2` DECIMAL(5,0) NULL DEFAULT NULL,
  `posicao_1a` DECIMAL(5,0) NULL DEFAULT NULL,
  `faltante_dia_1` CHAR(1) NULL DEFAULT NULL,
  `faltante_dia_2` CHAR(1) NULL DEFAULT NULL,
  `faltante_dia_3` CHAR(1) NULL DEFAULT NULL,
  `id_lingua` TINYINT(4) NULL DEFAULT NULL,
  `id_local` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_candidato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`categoria` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_categoria` TINYINT(4) NOT NULL,
  `nome_categoria` VARCHAR(48) NULL DEFAULT NULL,
  `perc_vagas` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`unidade_federativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`unidade_federativa` (
  `id_unidade_federativa` CHAR(2) NOT NULL,
  `nome_unidade_federativa` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_unidade_federativa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`cidade` (
  `id_cidade` INT(11) NOT NULL,
  `nome_municipio` VARCHAR(40) NOT NULL,
  `id_unidade_federativa` CHAR(2) NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_cidade_unidade_federativa` (`id_unidade_federativa` ASC),
  CONSTRAINT `fk_cidade_unidade_federativa`
    FOREIGN KEY (`id_unidade_federativa`)
    REFERENCES `vestibular`.`unidade_federativa` (`id_unidade_federativa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`estabelecimento_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`estabelecimento_ensino` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_estabelecimento_ensino` CHAR(4) NOT NULL,
  `nome_estabelecimento` VARCHAR(40) NULL DEFAULT NULL,
  `rede` TINYINT(4) NULL DEFAULT NULL,
  `endereco` VARCHAR(40) NULL DEFAULT NULL,
  `complemento` VARCHAR(40) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `id_cidade` INT(11) NULL DEFAULT NULL,
  `cep` DECIMAL(8,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_estabelecimento_ensino`),
  INDEX `fk_estabelecimento_ensino_cidade` (`id_cidade` ASC),
  CONSTRAINT `fk_estabelecimento_ensino_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `vestibular`.`cidade` (`id_cidade`),
  CONSTRAINT `fk_estabelecimento_ensino_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`disciplina_prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`disciplina_prova` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_prova` TINYINT(4) NOT NULL,
  `id_disciplina` TINYINT(4) NOT NULL,
  `nome_disciplina` VARCHAR(40) NOT NULL,
  `numero_questoes_subjetivas` SMALLINT(6) NULL DEFAULT NULL,
  `numero_questoes_objetivas` SMALLINT(6) NULL DEFAULT NULL,
  `acerto_minimo` DECIMAL(5,2) NULL DEFAULT NULL,
  `media_minima` DECIMAL(5,2) NULL DEFAULT NULL,
  `media_disciplina` DECIMAL(5,2) NULL DEFAULT NULL,
  `numero_questao_inicial` TINYINT(4) NULL DEFAULT NULL,
  `numero_questao_final` TINYINT(4) NULL DEFAULT NULL,
  `media_disciplina_aprovados` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_prova`, `id_disciplina`),
  CONSTRAINT `fk_disciplina_prova_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`lingua_estrangeira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`lingua_estrangeira` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_lingua` TINYINT(4) NOT NULL,
  `descricao_lingua` VARCHAR(10) NULL DEFAULT NULL,
  `media_lingua` DECIMAL(5,2) NULL DEFAULT NULL,
  `qtidade_questoes` TINYINT(4) NULL DEFAULT NULL,
  `media_aprovados` DECIMAL(5,2) NULL DEFAULT NULL,
  `id_prova` TINYINT(4) NULL DEFAULT NULL,
  `id_disciplina` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_lingua`),
  INDEX `fk_lingua_estrangeira_disc_prova` (`id_evento` ASC, `id_prova` ASC, `id_disciplina` ASC),
  CONSTRAINT `fk_lingua_estrangeira_disc_prova`
    FOREIGN KEY (`id_evento` , `id_prova` , `id_disciplina`)
    REFERENCES `vestibular`.`disciplina_prova` (`id_evento` , `id_prova` , `id_disciplina`),
  CONSTRAINT `fk_lingua_estrangeira_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`local` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_local` SMALLINT(6) NOT NULL,
  `nome_local` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_local`),
  CONSTRAINT `fk_local_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`raca` (
  `id_raca` TINYINT(4) NOT NULL,
  `nome_raca` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_raca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`sexo` (
  `id_sexo` CHAR(1) NOT NULL,
  `nome_sexo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`candidato` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_candidato` DECIMAL(7,0) NOT NULL,
  `data_nascimento` DATETIME NULL DEFAULT NULL,
  `id_lingua` TINYINT(4) NULL DEFAULT NULL,
  `id_local` SMALLINT(6) NULL DEFAULT NULL,
  `mes_segundo_grau` TINYINT(4) NULL DEFAULT NULL,
  `ano_segundo_grau` SMALLINT(6) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `por_experiencia` CHAR(1) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `unidade_federativa` CHAR(2) NULL DEFAULT NULL,
  `grade_socioeconomico` VARCHAR(44) NULL DEFAULT NULL,
  `classificacao_geral` DECIMAL(6,0) NULL DEFAULT NULL,
  `estabelecimento_2grau` CHAR(4) NULL DEFAULT NULL,
  `acertos_total` DECIMAL(5,2) NULL DEFAULT NULL,
  `raca` TINYINT(4) NULL DEFAULT NULL,
  `id_categoria` TINYINT(4) NULL DEFAULT NULL,
  `ensino_publico` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_candidato`),
  INDEX `fk_candidato_lingua` (`id_evento` ASC, `id_lingua` ASC),
  INDEX `fk_candidato_local` (`id_evento` ASC, `id_local` ASC),
  INDEX `fk_candidato_sexo` (`sexo` ASC),
  INDEX `fk_candidato_unidade_federativa` (`unidade_federativa` ASC),
  INDEX `fk_candidato_estabelecimento_ensino` (`id_evento` ASC, `estabelecimento_2grau` ASC),
  INDEX `fk_candidato_raca` (`raca` ASC),
  INDEX `fk_candidato_categoria` (`id_evento` ASC, `id_categoria` ASC),
  CONSTRAINT `fk_candidato_categoria`
    FOREIGN KEY (`id_evento` , `id_categoria`)
    REFERENCES `vestibular`.`categoria` (`id_evento` , `id_categoria`),
  CONSTRAINT `fk_candidato_estabelecimento_ensino`
    FOREIGN KEY (`id_evento` , `estabelecimento_2grau`)
    REFERENCES `vestibular`.`estabelecimento_ensino` (`id_evento` , `id_estabelecimento_ensino`),
  CONSTRAINT `fk_candidato_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`),
  CONSTRAINT `fk_candidato_lingua`
    FOREIGN KEY (`id_evento` , `id_lingua`)
    REFERENCES `vestibular`.`lingua_estrangeira` (`id_evento` , `id_lingua`),
  CONSTRAINT `fk_candidato_local`
    FOREIGN KEY (`id_evento` , `id_local`)
    REFERENCES `vestibular`.`local` (`id_evento` , `id_local`),
  CONSTRAINT `fk_candidato_raca`
    FOREIGN KEY (`raca`)
    REFERENCES `vestibular`.`raca` (`id_raca`),
  CONSTRAINT `fk_candidato_sexo`
    FOREIGN KEY (`sexo`)
    REFERENCES `vestibular`.`sexo` (`id_sexo`),
  CONSTRAINT `fk_candidato_unidade_federativa`
    FOREIGN KEY (`unidade_federativa`)
    REFERENCES `vestibular`.`unidade_federativa` (`id_unidade_federativa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`opcao_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`opcao_candidato` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_candidato` DECIMAL(7,0) NOT NULL,
  `id_opcao` CHAR(2) NOT NULL,
  `codigo_opcao` SMALLINT(6) NULL DEFAULT NULL,
  `opcao_invalida` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_candidato`, `id_opcao`),
  CONSTRAINT `fk_opcao_candidato_candidato`
    FOREIGN KEY (`id_evento` , `id_candidato`)
    REFERENCES `vestibular`.`candidato` (`id_evento` , `id_candidato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`candidato_classificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`candidato_classificado` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_candidato` DECIMAL(7,0) NOT NULL,
  `id_opcao` CHAR(2) NOT NULL,
  `id_categoria` TINYINT(4) NULL DEFAULT NULL,
  `codigo_opcao` SMALLINT(6) NULL DEFAULT NULL,
  `periodo` TINYINT(4) NULL DEFAULT NULL,
  `ordem_classificacao` DECIMAL(5,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_candidato`),
  INDEX `fk_candidato_classificado_opcao_candidato` (`id_evento` ASC, `id_candidato` ASC, `id_opcao` ASC),
  INDEX `fk_candidato_classificado_categoria` (`id_evento` ASC, `id_categoria` ASC),
  CONSTRAINT `fk_candidato_classificado_candidato`
    FOREIGN KEY (`id_evento` , `id_candidato`)
    REFERENCES `vestibular`.`candidato` (`id_evento` , `id_candidato`),
  CONSTRAINT `fk_candidato_classificado_categoria`
    FOREIGN KEY (`id_evento` , `id_categoria`)
    REFERENCES `vestibular`.`categoria` (`id_evento` , `id_categoria`),
  CONSTRAINT `fk_candidato_classificado_opcao_candidato`
    FOREIGN KEY (`id_evento` , `id_candidato` , `id_opcao`)
    REFERENCES `vestibular`.`opcao_candidato` (`id_evento` , `id_candidato` , `id_opcao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`grade_socioeconomico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`grade_socioeconomico` (
  `id_evento` SMALLINT(6) NOT NULL,
  `numero_questao` TINYINT(4) NOT NULL,
  `posicao_inicial` TINYINT(4) NULL DEFAULT NULL,
  `tamanho` TINYINT(4) NULL DEFAULT NULL,
  `literal_questao` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `numero_questao`),
  CONSTRAINT `fk_grade_socioeconomico_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `vestibular`.`evento` (`id_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`codigo_questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`codigo_questionario` (
  `id_evento` SMALLINT(6) NOT NULL,
  `numero_questao` TINYINT(4) NOT NULL,
  `id_codigo` CHAR(3) NOT NULL,
  `descricao_codigo` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `numero_questao`, `id_codigo`),
  CONSTRAINT `fk_codigo_questionario_grade_socio_econ`
    FOREIGN KEY (`id_evento` , `numero_questao`)
    REFERENCES `vestibular`.`grade_socioeconomico` (`id_evento` , `numero_questao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vestibular`.`ponto_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vestibular`.`ponto_candidato` (
  `id_evento` SMALLINT(6) NOT NULL,
  `id_candidato` DECIMAL(7,0) NOT NULL,
  `acertos_biologia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_geografia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_matematica` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_lingua_estrangeira` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_portugues` DECIMAL(5,2) NULL DEFAULT NULL,
  `nota_redacao` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_fisica` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_historia` DECIMAL(5,2) NULL DEFAULT NULL,
  `acertos_quimica` DECIMAL(5,2) NULL DEFAULT NULL,
  `faltante_dia_1` CHAR(1) NULL DEFAULT NULL,
  `faltante_dia_2` CHAR(1) NULL DEFAULT NULL,
  `faltante_dia_3` CHAR(1) NULL DEFAULT NULL,
  `por_experiencia` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`, `id_candidato`),
  CONSTRAINT `fk_ponto_candidato_candidato`
    FOREIGN KEY (`id_evento` , `id_candidato`)
    REFERENCES `vestibular`.`candidato` (`id_evento` , `id_candidato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
